services:
# TODO delete before push
# connect with url : mysql://<user>:<password>@<host>:<port>/<database>
# del the persistant files
  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    ports:
      - "8444:4983"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./data/drizzle-gateway:/app
    networks:
      - ft
# NGINX
  nginx:
    image: ft_nginx
    build: ./services/nginx
    environment:
      ALLOWED_METHODS: "GET HEAD POST OPTIONS PUT DELETE PATCH"
    ports: #TODO 443 80
      - "8080:8080"
      - "8443:8443"
    depends_on:
      frontend:
        condition: service_healthy
      users_service:
        condition: service_healthy
      api_service:
        condition: service_healthy
    networks:
      - ft
    restart: unless-stopped
# VAULT
  vault:
    image: ft_vault
    build: ./services/vault
    env_file:
      - ./env/.env
    secrets:
      - db_root_password
    volumes: 
      - vault_data:/vault/file
      - approle:/vault/approle
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/approle/.ready"]
      interval: 1s
      timeout: 3s
      retries: 60
      start_period: 5s
    networks:
      - ft
    restart: unless-stopped
# DATABASE
  database:
    image: ft_database
    build: ./services/database
    env_file:
      - ./env/.env
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 2s
      timeout: 5s
      retries: 25
    networks:
      - ft
    restart: unless-stopped
# FRONTEND
  frontend:
    image: ft_frontend
    build: ./services/frontend
    networks:
      - ft
    restart: unless-stopped
# USERS_SERVICE
  users_service:
    image: ft_users
    build: ./services/backend/users_service
    env_file:
      - ./env/.env
    depends_on:
      database:
        condition: service_healthy
      users_service_agent:
        condition: service_healthy
    volumes:
      - users_service_creds:/vault/secrets:ro
    networks:
      - ft
    restart: unless-stopped
# USERS SERVICE AGENT
  users_service_agent:
    image: ft_users_agent
    build: ./services/vault/agents/users_service
    depends_on:
      vault:
        condition: service_healthy
    volumes:
      - approle:/vault/approle:ro
      - users_service_creds:/vault/secrets
    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/secrets/db_creds.json"]
      interval: 1s
      timeout: 3s
      retries: 60
      start_period: 10s
    networks:
      - ft
    restart: unless-stopped
# API SERVICE
  api_service:
    image: ft_api
    build: ./services/backend/api_service
    env_file:
      - ./env/.env
    depends_on:
      database:
        condition: service_healthy
      api_service_agent:
        condition: service_healthy
    volumes:
      - api_service_creds:/vault/secrets:ro
    networks:
      - ft
    restart: unless-stopped
# API SERVICE AGENT
  api_service_agent:
    image: ft_api_agent
    build: ./services/vault/agents/api_service
    depends_on:
      vault:
        condition: service_healthy
    volumes:
      - approle:/vault/approle:ro
      - api_service_creds:/vault/secrets
    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/secrets/db_creds.json"]
      interval: 1s
      timeout: 3s
      retries: 60
      start_period: 10s
    networks:
      - ft
    restart: unless-stopped

networks:
  ft:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mariadb

  vault_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/vault

  approle:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

  users_service_creds:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

  api_service_creds:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:
  db_root_password:
    file: ./env/secrets/db_root_password.txt