services:
  nginx:
    build: ./services/nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - frontend
      - auth_service
    networks:
      - transcendence
    restart: unless-stopped

  database:
    build: ./services/database
    env_file:
      - ./env/.env
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build: ./services/frontend
    expose:
      - "80"
    networks:
      - transcendence
    restart: unless-stopped

  auth_service:
    build: ./services/backend/auth_service
    env_file:
      - ./env/.env
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    expose:
      - "3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mariadb

secrets:
  db_password:
    file: ./env/secrets/db_password.txt