# run Vite dev server with hot reload
FROM    node:24-alpine

WORKDIR /app

COPY    app/package.json ./
RUN     npm install

COPY    app/ .

EXPOSE  5173

HEALTHCHECK --interval=5s --timeout=3s --retries=10 --start-period=15s \
	CMD nc -z 127.0.0.1 5173 || exit 1

RUN		chown -R node:node /app

USER	node

CMD     ["npm", "run", "dev"]
