# run Vite dev server with hot reload
FROM    node:24-alpine

WORKDIR /app

COPY    app/package.json ./
RUN     npm install

COPY    app/ .

EXPOSE  5173

RUN		chown -R node:node /app

USER	node

CMD     ["npm", "run", "dev"]
