
FROM    hashicorp/vault:2.0

USER    root

RUN     apk add --no-cache gettext openssl

COPY    tools/entrypoint.dev.sh /tools/entrypoint.sh
RUN     chmod +x /tools/entrypoint.sh

COPY    policies/ /vault/policies/

USER    vault

EXPOSE  8200

ENTRYPOINT ["/tools/entrypoint.sh"]
CMD        ["server", "-dev", "-dev-listen-address=0.0.0.0:8200"]