apiVersion: 1
groups:
    - orgId: 1
      name: critical
      folder: alerte
      interval: 1m
      rules:
        - uid: dfvgv54azn11cc
          title: service
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: up
                instant: true
                intervalMs: 1000
                legendFormat: '{{job}}'
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: empty
    - orgId: 1
      name: warning
      folder: alerte
      interval: 1m
      rules:
        - uid: efvgve95ww740e
          title: Latence anormale des requêtes
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: |-
                    histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le,
                      job))
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: empty
        - uid: ffvgvj8e5454wf
          title: mysql_global_status_threads_connected
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: mysql_global_status_threads_connected
                instant: true
                intervalMs: 1000
                legendFormat: '{{job}}'
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 50
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: empty
        - uid: afvgvn5vk2jnkb
          title: Requêtes SQL lentes détectées
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: rate(mysql_global_status_slow_queries[5m])
                instant: true
                intervalMs: 1000
                legendFormat: '{{job}}'
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: empty
        - uid: bfvgvqyl5idxcb
          title: Requêtes SQL lentes détectées
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: rate(mysql_global_status_slow_queries[5m])
                instant: true
                intervalMs: 1000
                legendFormat: '{{job}}'
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: empty
